name: real_time_chatify
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  firebase_auth: ^4.6.3
  firebase_analytics: ^10.4.3
  cloud_firestore: ^4.8.2
  provider: ^6.0.5
  get_it: ^7.6.0
  file_picker: ^5.3.2
  flutter_spinkit: ^5.2.0
  timeago: ^3.5.0
  flutter_keyboard_visibility: ^5.4.1
  get: ^4.6.5
  shared_preferences: ^2.2.0
  connectivity_plus: ^4.0.2
  flutter_local_notifications: ^15.1.0+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

